package cs

const (
	COMMON_RESULT_SUCCESS = 0
	COMMON_RESULT_FAILED = 1

	//COMMON_NOTIFY_TYPE
	COMMON_NOTIFY_T_FILE_ADDR = 1
	COMMON_NOTIFY_T_ADD_MEM   = 2
	COMMON_NOTIFY_T_DEL_MEM   = 3
	COMMON_NOTIFY_T_HEAD_URL  = 4
	COMMON_NOTIFY_T_ENTER_GROUP = 5 //self enter group


	//COMMON_QUERY_TYPE
	COMMON_QUERY_OWN_GRP_SNAP = 0
	COMMON_QUERY_SET_CLI_HEART = 1
)
